
matrix:
    include:

        - dist: xenial
          language: generic
          env: TEST_NAME=01_sanity
        
        - os: osx
          language: generic
          env: TEST_NAME=01_sanity

        - os: windows
          language: generic
          env: TEST_NAME=01_sanity

script:
  - ansible --version
  - cd $TRAVIS_BUILD_DIR/tests/$TEST_NAME && ./start.sh
