
# check if java is correct

- command: /usr/libexec/java_home -v 1.8
  ignore_errors: yes
  register: java_found

- set_fact:
    java8_installed: "{{ java_found.rc == 0 | bool }}"
    __force_install: "{{ force_install | default('no') | bool }}"

# install java

- name: install java8 if not installed
  block: 

    - name: make sure temp folder exists
      file: 
        path: "{{ temp_folder }}"
        state: directory

    - name: download zip from s3 url
      get_url:
        url: "{{ s3_download_url }}"
        dest: "{{ temp_folder }}/{{ installer_file_name }}"
        
    - set_fact:
        mount_point: "{{ temp_folder }}/tmp-{{ installer_file_name }}"
        mount_point_regexp: "tmp-{{ installer_file_name }}"

    - name: make sure mountpoint folder exists
      file: 
        path: "{{ mount_point }}"
        state: directory

    - command: "hdiutil attach {{ temp_folder }}/{{ installer_file_name }} -nobrowse -mountpoint {{ mount_point }}"

    - name: find volume name
      find:
        paths: "{{ mount_point }}"
        patterns: "*.app"
        file_type: any
      register: files_matched

    - debug: var=files_matched

    - set_fact:
        app_file_path: "{{ files_matched.files[0].path }}"
        app_file_name: "{{ files_matched.files[0].path | basename }}"

    - command: "/usr/sbin/installer -pkg '{{ app_file_path }}/Contents/Resources/JavaAppletPlugin.pkg' -target /"
      become: yes

    - command: "diskutil umount {{ mount_point }}"

    - name: Ansible delete file wildcard example
      shell: "rm -rf {{ temp_folder }}/{{ mount_point_regexp }}"

  when: __force_install or not java8_installed
