
- name: install Chocolatey
  win_chocolatey:
    name: chocolatey
    state: latest

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: install java from chocolatey 
  win_chocolatey: 
    name: jdk8
    version: 8.0.201
    state: present
